use rd_staging;
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `rdInsCDSData`(
  PatientID varchar(150),
  PatientFamilyName varchar(150),
  PatientGivenName varchar(150),
  PatientTitle varchar(150),
  PatientDOB varchar(150),
  PatientSex varchar(5),
  PatientStreetAddress varchar(150),
  PatientCity varchar(150),
  PatientPostalCode varchar(150),
  PatientState varchar(150),
  PatientCountry varchar(150),
  PatientStatus varchar(150),
  PatientPregnancyFlag varchar(10),
  PatientFastingFlag varchar(10),
  EpisodeID varchar(150),
  EpisodeOrderedTests varchar(2000),
  EpisodeDateTime datetime,
  EpisodeClinicalNotes TEXT,
  AccountType varchar(150),
  AccountClass varchar(150),
  BillTo varchar(150),
  BillingAddress varchar(150),
  PatientPublicHealthIdentifier varchar(150),
  EpisodePublicScheduleCode varchar(1000),
  PatientPrivateHealthFundName varchar(150),
  PatientPrivateHealthFundID varchar(150),
  ReqPhysicianID varchar(150),
  ReqPhysicianName varchar(150),
  ReqPhysicianSpeciality varchar(150),
  ReqPhysicianDeliveryAddress varchar(150),
  SugeryName varchar(150),
  SurgeryCode varchar(150),
  SurgeryAddress varchar(150),
  SurgeryPostalCode varchar(150),
  CopyPhysicianIDList varchar(150),
  CopyPhysicianNameList varchar(150),
  PanelIndicator varchar(5),
  PanelID varchar(150),
  PanelName varchar(150),
  SampleID varchar(150),
  SampleFluidType varchar(150),
  SampleOriginLocation varchar(150),
  SampleOriginSubLocation varchar(150),
  SampleCollectionDateTime varchar(150),
  SampleCollectionMethod varchar(150),
  TestSiteSampleReceivedDateTime varchar(150),
  TestLISCode varchar(150),
  TestLISName varchar(150),
  TestValue varchar(2000),
  TestNormalRange varchar(150),
  TestUnits varchar(150),
  TestPriority varchar(150),
  TestDepartment varchar(150),
  TestInstrument varchar(150),
  TestRequestSite varchar(150),
  TestSite varchar(150),
  TestType varchar(150),
  AbnormalFlag varchar(5),
  TestOrderedDateTime varchar(150),
  TestAnalyzerCompletionDateTime varchar(150),
  TestResultFirstReviewedDateTime varchar(150),
  TestResultReleasedDateTime varchar(150)
)
SQL SECURITY INVOKER
BEGIN
declare MESSAGE_ID int;
insert into cds_data
(
PatientID,
PatientFamilyName,
PatientGivenName,
PatientTitle,
PatientDOB,
PatientSex,
PatientStreetAddress,
PatientCity,
PatientPostalCode,
PatientState,
PatientCountry,
PatientStatus,
PatientPregnancyFlag,
PatientFastingFlag,
EpisodeID,
EpisodeOrderedTests,
EpisodeDateTime,
EpisodeClinicalNotes,
AccountType,
AccountClass,
BillTo,
BillingAddress,
PatientPublicHealthIdentifier,
EpisodePublicScheduleCode,
PatientPrivateHealthFundName,
PatientPrivateHealthFundID,
ReqPhysicianID,
ReqPhysicianName,
ReqPhysicianSpeciality,
ReqPhysicianDeliveryAddress,
SugeryName,
SurgeryCode,
SurgeryAddress,
SurgeryPostalCode,
CopyPhysicianIDList,
CopyPhysicianNameList,
PanelIndicator,
PanelID,
PanelName,
SampleID,
SampleFluidType,
SampleOriginLocation,
SampleOriginSubLocation,
SampleCollectionDateTime,
SampleCollectionMethod,
TestSiteSampleReceivedDateTime,
TestLISCode,
TestLISName,
TestValue,
TestNormalRange,
TestUnits,
TestPriority,
TestDepartment,
TestInstrument,
TestRequestSite,
TestSite,
TestType,
AbnormalFlag,
TestOrderedDateTime,
TestAnalyzerCompletionDateTime,
TestResultFirstReviewedDateTime,
TestResultReleasedDateTime
)

values
(
PatientID,
PatientFamilyName,
PatientGivenName,
PatientTitle,
PatientDOB,
PatientSex,
PatientStreetAddress,
PatientCity,
PatientPostalCode,
PatientState,
PatientCountry,
PatientStatus,
PatientPregnancyFlag,
PatientFastingFlag,
EpisodeID,
EpisodeOrderedTests,
EpisodeDateTime,
EpisodeClinicalNotes,
AccountType,
AccountClass,
BillTo,
BillingAddress,
PatientPublicHealthIdentifier,
EpisodePublicScheduleCode,
PatientPrivateHealthFundName,
PatientPrivateHealthFundID,
ReqPhysicianID,
ReqPhysicianName,
ReqPhysicianSpeciality,
ReqPhysicianDeliveryAddress,
SugeryName,
SurgeryCode,
SurgeryAddress,
SurgeryPostalCode,
CopyPhysicianIDList,
CopyPhysicianNameList,
PanelIndicator,
PanelID,
PanelName,
SampleID,
SampleFluidType,
SampleOriginLocation,
SampleOriginSubLocation,
SampleCollectionDateTime,
SampleCollectionMethod,
TestSiteSampleReceivedDateTime,
TestLISCode,
TestLISName,
TestValue,
TestNormalRange,
TestUnits,
TestPriority,
TestDepartment,
TestInstrument,
TestRequestSite,
TestSite,
TestType,
AbnormalFlag,
TestOrderedDateTime,
TestAnalyzerCompletionDateTime,
TestResultFirstReviewedDateTime,
TestResultReleasedDateTime
);
SELECT MESSAGE_ID = LAST_INSERT_ID();
END$$
DELIMITER ;
